### ISSUE TITLE
Reparasjon av PDF generator

### ISSUE THREAD

**Issue by FinnurO** [Altinn/altinn-roadmap#30]
Sammendrag
Dagens (mars 22) PDF generering i Altinn 3 er beheftet med en rekke feil og mangler. Det planlegges å gjøre en omskrivning av generatoren, men som en første tilnærming til utfordringene vil en del enkle og grunnleggende problemer rettes.

Ønsket resultat
Arbeidet vil ha fjernet de mest grunnleggende og minst kostbare feilene.
(scope satt 18.03.2022).

**Comment by OddArneSaetervik** [comment]
Dagens (mars 22) PDF generering i ALtinn 3 er beheftet med en rekke feil og mangler. Det vurderes/planlegges å gjøre en omskrivning av generatoren, men som en første tilnærming til utfordringene vil en del enkle og grunnleggende problemer rettes.

**Comment by OddArneSaetervik** [comment]
https://github.com/Altinn/altinn-studio/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fpdf
https://github.com/Altinn/altinn-studio/issues/2320 i denne?

**Comment by SandGrainOne** [comment]
@OddArneSaetervik Er dette en sak vi kan lukke? Alle assosierte issues er lukket.
